export const RESET_REDUCER = 'RESET_REDUCER';
export const COMMON_SHOW_NOTIFICATION = 'COMMON_SHOW_NOTIFICATION';

export const GET_BRACKET_BOARD_INFO = 'GET_BRACKET_BOARD_INFO';

export const LOGIN = 'LOGIN';
export const SIGNUP = 'SIGNUP';

export const SET_HOVERING_TEAM = 'SET_HOVERING_TEAM';
export const SET_BRACKET_STATUS = 'SET_BRACKET_STATUS';

export const SUBMIT_FORM = 'SUBMIT_FORM';