export const RESET_REDUCER = 'RESET_REDUCER';
export const COMMON_SHOW_NOTIFICATION = 'COMMON_SHOW_NOTIFICATION';

export const GET_BRACKET_BOARD_INFO = 'GET_BRACKET_BOARD_INFO';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SIGNUP = 'SIGNUP';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';

export const SET_HOVERING_TEAM = 'SET_HOVERING_TEAM';
export const SET_BRACKET_STATUS = 'SET_BRACKET_STATUS';

export const QUERY_USER_INFO = 'QUERY_USER_INFO';
export const QUERY_TOURNAMENT_INFO = 'QUERY_TOURNAMENT_INFO';
export const QUERY_LIST_TOURNAMENT_OF_USER = 'QUERY_LIST_TOURNAMENT_OF_USER';
export const QUERY_LIST_TEAM_OF_USER = 'QUERY_LIST_TEAM_OF_USER';

export const CHECK_USERNAME_EXISTED = 'CHECK_USERNAME_EXISTED';

export const SUBMIT_FORM = 'SUBMIT_FORM';